import {useEffect,useState} from 'react';
import {getAgreementsIndicators,type AgreementsIndicatorsData} from './agreementsIndicatorsService';
import {formatCurrencyBR,formatNumberBR} from './formatters';
import {Bars,Metric,Panel} from './PortfolioParts';
export function AgreementsIndicatorsSection(){
 const [data,setData]=useState<AgreementsIndicatorsData|null>(null),[origin,setOrigin]=useState(''),[page,setPage]=useState(1),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let current=true;setData(null);setError('');getAgreementsIndicators(page,origin).then(value=>{if(current)setData(value);}).catch(()=>{if(current)setError('Não foi possível carregar os acordos.');});return()=>{current=false;};},[page,origin,retry]);
 return <section className="executive-agreements" id="executive-agreements"><header className="section-heading"><div><p className="eyebrow">Visão executiva</p><h2>Acordos em tratativa</h2><p>Resultados da carteira de acordos. Preditivos em saneamento são acompanhados separadamente.</p></div><label>Origem<select value={origin} onChange={e=>{setOrigin(e.target.value);setPage(1);}}><option value="">Todas as origens</option><option value="terceirizado">Terceirizado</option><option value="interno">Interno</option></select></label></header>
 {error?<div className="error-state" role="alert">{error}<button onClick={()=>setRetry(v=>v+1)}>Tentar novamente</button></div>:!data?<div className="loading-state" role="status">Carregando acordos…</div>:<>
 <div className="metrics metrics-five"><Metric label="Total de acordos" value={formatNumberBR(data.summary.total)}/><Metric label="Ticket médio das propostas" value={data.summary.ticket_medio===null?'—':formatCurrencyBR(data.summary.ticket_medio)}/><Metric label="Acordos fechados" value={formatNumberBR(data.summary.fechados)}/><Metric label="Em negociação" value={formatNumberBR(data.summary.em_negociacao)}/><Metric label="Acordos recusados" value={formatNumberBR(data.summary.recusados)}/></div>
 <div className="composition-grid"><Panel title="Por situação"><Bars items={data.por_situacao}/></Panel><Panel title="Por tarefa"><Bars items={data.por_tarefa}/></Panel><Panel title="Por tipo"><Bars items={data.por_tipo}/></Panel></div>
 <details className="agreement-records"><summary>Consultar {formatNumberBR(data.table.total)} registros de acordos</summary><div className="table-scroll"><table><thead><tr><th>CNJ</th><th>Situação</th><th>Tipo</th><th>Tarefa</th><th>Proposta</th><th>Origem</th></tr></thead><tbody>{data.table.rows.length?data.table.rows.map(row=><tr key={row.id}><td>{row.cnj||'—'}</td><td>{row.situacao||'—'}</td><td>{row.tipo||'—'}</td><td>{row.tarefa||'—'}</td><td>{row.proposta===null?'—':formatCurrencyBR(row.proposta)}</td><td>{row.origem_acordo}</td></tr>):<tr><td colSpan={6}>Nenhum acordo nesta origem.</td></tr>}</tbody></table></div><div className="pagination"><span>Página {page} de {Math.max(1,data.table.total_pages)}</span><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</button><button disabled={page>=data.table.total_pages} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></details>
 </>}
 </section>;
}
