import {useEffect,useRef,useState} from 'react';
import {Area,CartesianGrid,ComposedChart,Line,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {getCarteiraData,type CarteiraFilters,type CarteiraData} from './carteiraService';
import {formatNumberBR,formatDateBR} from './formatters';
import {AgreementsIndicatorsSection} from './AgreementsIndicatorsSection';
import {Bars,Metric,Panel} from './PortfolioParts';
import './carteira.css';
const initial:CarteiraFilters={entryStart:'',entryEnd:'',resolutionStart:'',resolutionEnd:'',state:'',resolution:'',cnj:'',integration:'',product:'',situation:'',attention:'',groupBy:'month',page:1,pageSize:25,sortBy:'date',sortDirection:'desc'};
const tabs=['Carteira Processual','Entradas','Encerramentos','Auditoria'];
export function CarteiraProcessualPage(){
 const [filters,setFilters]=useState<CarteiraFilters>({...initial,cnj:window.MBA_PORTFOLIO_SEARCH||''});
 const [data,setData]=useState<CarteiraData|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0),[tab,setTab]=useState(0),[dateType,setDateType]=useState('entry');
 const table=useRef<HTMLElement>(null);
 useEffect(()=>{if(window.MBA_PORTFOLIO_SECTION==='agreements'){document.getElementById('executive-agreements')?.scrollIntoView();window.MBA_PORTFOLIO_SECTION=undefined;}},[]);
 useEffect(()=>{let current=true;setLoading(true);setError('');getCarteiraData(filters).then(value=>{if(current)setData(value);}).catch(()=>{if(current){setData(null);setError('Não foi possível carregar a carteira. Tente novamente.');}}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[filters,retry]);
 const update=(values:Partial<CarteiraFilters>)=>setFilters(f=>({...f,...values,page:values.page??1}));
 useEffect(()=>{const search=(event:Event)=>{setFilters(f=>({...f,cnj:(event as CustomEvent<string>).detail,page:1}));table.current?.scrollIntoView({behavior:'smooth'});};window.addEventListener('mba:portfolio-search',search);return()=>window.removeEventListener('mba:portfolio-search',search);},[]);
 const selectTab=(index:number)=>{setTab(index);setDateType(index===2?'resolution':'entry');update({...initial,cnj:filters.cnj,attention:index===3?'divergent':''});};
 const periodStart=dateType==='entry'?filters.entryStart:filters.resolutionStart,periodEnd=dateType==='entry'?filters.entryEnd:filters.resolutionEnd;
 const changeDateType=(type:string)=>{setDateType(type);update({entryStart:type==='entry'?periodStart:'',entryEnd:type==='entry'?periodEnd:'',resolutionStart:type==='resolution'?periodStart:'',resolutionEnd:type==='resolution'?periodEnd:''});};
 const attention=(kind:CarteiraFilters['attention'])=>{update({attention:kind});table.current?.scrollIntoView({behavior:'smooth'});};
 const fnum=(n:number|undefined)=>n===undefined?'—':formatNumberBR(n);
 const low=data?.attention.closures_below_average;
 return <div className="portfolio"><nav className="context-nav" aria-label="Gestão Processual">{tabs.map((label,index)=><button key={label} aria-current={tab===index?'page':undefined} onClick={()=>selectTab(index)}>{label}</button>)}</nav>
 <header className="portfolio-heading"><div><p className="eyebrow">Gestão Processual</p><h1>{tabs[tab]}</h1><p>Visão consolidada da base operacional.</p></div><div className="data-status"><span className={error?'status-dot error':'status-dot'}/>{loading?'Atualizando…':error?'Dados indisponíveis':'Dados carregados'}<small>{data?.updated_at?`Última atualização: ${new Date(data.updated_at).toLocaleString('pt-BR')}`:'Última atualização não informada'}</small></div></header>
 <section className="portfolio-filters" aria-label="Filtros da carteira"><label>Tipo de data<select value={dateType} onChange={e=>changeDateType(e.target.value)}><option value="entry">Entrada</option><option value="resolution">Encerramento</option></select></label><fieldset className="period-filter"><legend>Período</legend><input aria-label="Início do período" type="date" value={periodStart} max={periodEnd||undefined} onChange={e=>update(dateType==='entry'?{entryStart:e.target.value}:{resolutionStart:e.target.value})}/><span>até</span><input aria-label="Fim do período" type="date" value={periodEnd} min={periodStart||undefined} onChange={e=>update(dateType==='entry'?{entryEnd:e.target.value}:{resolutionEnd:e.target.value})}/></fieldset>
 <label>UF<select value={filters.state} onChange={e=>update({state:e.target.value})}><option value="">Todas</option>{data?.filters.states.map(v=><option key={v}>{v}</option>)}</select></label><label>Produto<select value={filters.product} onChange={e=>update({product:e.target.value})}><option value="">Todos</option>{data?.filters.products.map(v=><option key={v}>{v}</option>)}</select></label><label>Situação<select value={filters.situation} onChange={e=>update({situation:e.target.value as CarteiraFilters['situation']})}><option value="">Todas</option><option value="active">Ativo</option><option value="closed">Encerrado</option><option value="unknown">Não informado</option></select></label><label>Tipo de encerramento<select value={filters.resolution} onChange={e=>update({resolution:e.target.value})}><option value="">Todos</option>{data?.filters.resolutions.map(v=><option key={v}>{v}</option>)}</select></label><button className="text-button" onClick={()=>{setFilters(initial);setDateType('entry');}}>Limpar</button></section>
 {error?<div className="error-state" role="alert">{error}<button onClick={()=>setRetry(v=>v+1)}>Tentar novamente</button></div>:<div aria-busy={loading} className={loading?'portfolio-content is-loading':'portfolio-content'}>
 <section className="metrics"><Metric label="Total de processos" value={fnum(data?.summary.total)}/><Metric label="Processos ativos" value={fnum(data?.summary.active)}/><Metric label="Processos encerrados" value={fnum(data?.summary.closed)}/><Metric label="Aging médio" value={data?.summary.aging_mean==null?'—':`${data.summary.aging_mean.toLocaleString('pt-BR',{maximumFractionDigits:1})} dias`} note="Carteira ativa"/></section>
 {Boolean(data?.summary.unknown)&&<p className="quality-note">{fnum(data?.summary.unknown)} processos com situação não informada.</p>}
 <div className="evolution-grid"><Panel title="Entradas × Encerramentos"><div className="chart-toolbar"><span><i className="legend-entry"/>Entradas <i className="legend-closed"/>Encerramentos</span><label className="sr-only" htmlFor="group-by">Agrupamento</label><select id="group-by" value={filters.groupBy} onChange={e=>update({groupBy:e.target.value as CarteiraFilters['groupBy']})}><option value="month">Por mês</option><option value="week">Por semana</option><option value="day">Por dia</option></select></div>{data?.charts.timeline.length?<div className="timeline"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data.charts.timeline} margin={{top:12,right:12,left:0,bottom:8}}><CartesianGrid vertical={false} stroke="#e7edf3"/><XAxis dataKey="date" tickFormatter={v=>String(v).slice(0,7).split('-').reverse().join('/')} tick={{fontSize:13,fill:'#65758a'}} axisLine={false} tickLine={false} minTickGap={30}/><YAxis tick={{fontSize:13,fill:'#65758a'}} axisLine={false} tickLine={false} width={58}/><Tooltip labelFormatter={v=>formatDateBR(String(v))} formatter={(value,name)=>[formatNumberBR(Number(value)),name==='entries'?'Entradas':'Encerramentos']} contentStyle={{borderRadius:8,fontSize:14,border:'1px solid #e4eaf0'}}/><Area type="monotone" dataKey="entries" stroke="#1965c0" fill="#eaf2fc" strokeWidth={2}/><Line type="monotone" dataKey="closures" stroke="#243c56" strokeWidth={2} dot={false}/></ComposedChart></ResponsiveContainer></div>:<div className="empty-state">{loading?'Carregando evolução…':'Nenhum evento neste período.'}</div>}</Panel>
 <Panel title="Movimentação no período"><div className="movement"><div><span>Entradas</span><strong>{fnum(data?.movement.entries)}</strong></div><div><span>Encerramentos</span><strong>{fnum(data?.movement.closures)}</strong></div><div className="movement-balance"><span>Saldo da movimentação</span><strong>{data&&data.movement.balance>0?'+':''}{fnum(data?.movement.balance)}</strong></div></div><p className="quality-note">Eventos de entrada e encerramento no mesmo período. Situação consolidada conforme Benner.</p></Panel></div>
 <div className="composition-grid"><Panel title="Processos por produto"><Bars items={data?.charts.por_produto||[]}/></Panel><Panel title="Processos por UF"><Bars items={data?.charts.por_uf||[]}/></Panel><Panel title="Aging da carteira ativa"><Bars items={data?.charts.aging||[]}/></Panel></div>
 <section className="attention-section"><h2>Pontos de atenção</h2><div className="attention-list"><button onClick={()=>attention('aging')}><span>Aging acima de 180 dias</span><strong>{fnum(data?.attention.aging)} <span>↗</span></strong></button><button onClick={()=>attention('divergent')}><span>Divergência CPJ × Benner</span><strong>{fnum(data?.attention.divergent)} <span>↗</span></strong></button><button onClick={()=>attention('archive')}><span>Aptos a arquivamento</span><strong>{fnum(data?.attention.archive)} <span>↗</span></strong></button>{low?.available?<button disabled={!low.below} onClick={()=>{setDateType('resolution');update({entryStart:'',entryEnd:'',resolutionStart:low.start,resolutionEnd:low.end,attention:''});table.current?.scrollIntoView({behavior:'smooth'});}}><span>Encerramentos no último mês completo</span><strong>{low.below?'Abaixo da média ↗':'Dentro ou acima da média'}</strong></button>:<p>Comparativo de encerramentos: histórico insuficiente.</p>}</div></section>
 <section ref={table} className="portfolio-table" id="portfolio-table"><header className="section-heading"><div><h2>Base de processos</h2><p>{data?`${fnum(data.table.total)} registros`:'Carregando…'}{filters.attention&&' · Recorte de atenção aplicado'}</p></div><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;update({cnj:(form.elements.namedItem('cnj') as HTMLInputElement).value});}}><label className="sr-only" htmlFor="cnj-search">Buscar por CNJ</label><input id="cnj-search" name="cnj" placeholder="Buscar por CNJ" defaultValue={filters.cnj} key={filters.cnj}/><button>Buscar</button></form></header>{filters.attention&&<button className="text-button" onClick={()=>update({attention:''})}>Remover recorte de atenção</button>}
 <div className="table-scroll"><table><thead><tr>{[['CNJ','cnj'],['Produto','product'],['Entrada','date'],['UF','state'],['Aging','aging'],['Encerramento','date_resolution'],['Tipo de encerramento','resolution'],['CPJ','situation_cpj'],['Benner','situation_benner']].map(([label,key])=><th key={key} aria-sort={filters.sortBy===key?(filters.sortDirection==='asc'?'ascending':'descending'):'none'}><button onClick={()=>update({sortBy:key,sortDirection:filters.sortBy===key&&filters.sortDirection==='asc'?'desc':'asc'})}>{label}{filters.sortBy===key?' ↕':''}</button></th>)}</tr></thead><tbody>{loading?<tr><td colSpan={9}>Carregando registros…</td></tr>:data?.table.rows.length?data.table.rows.map(r=><tr key={r.id}><td>{r.cnj||'—'}</td><td>{r.product||'—'}</td><td>{r.date?formatDateBR(r.date):'—'}</td><td>{r.state||'—'}</td><td>{r.aging??'—'}</td><td>{r.date_resolution?formatDateBR(r.date_resolution):'—'}</td><td>{r.resolution||'—'}</td><td>{r.situation_cpj||'—'}</td><td>{r.situation_benner||'—'}</td></tr>):<tr><td colSpan={9}>Nenhum processo encontrado.</td></tr>}</tbody></table></div><footer className="pagination"><span>Página {filters.page} de {Math.max(1,data?.table.total_pages||1)}</span><button disabled={loading||filters.page<=1} onClick={()=>update({page:filters.page-1})}>Anterior</button><button disabled={loading||filters.page>=(data?.table.total_pages||1)} onClick={()=>update({page:filters.page+1})}>Próxima</button></footer></section>
 </div>}
 <AgreementsIndicatorsSection/>
 </div>;
}
