
/* MBA Backoffice reimagined. Prototype ONLY: no real sessions, credentials, APIs or financial data. */
const roles={
 analista:{name:'Analista',person:'Colaborador',initial:'AN',home:'Minha fila',nav:[['Minha fila','inbox'],['Operação','layers'],['Processos','folder'],['Meu desempenho','trend']]},
 supervisor:{name:'Supervisor',person:'Supervisão',initial:'SV',home:'Central operacional',nav:[['Central operacional','layout'],['Fila da equipe','inbox'],['Operação','layers'],['Encerramentos','layers'],['Resultados','trend'],['Processos','folder']]},
 gerente:{name:'Gerente',person:'Gestão',initial:'GE',home:'Visão executiva',nav:[['Visão executiva','layout'],['Ranking','trend'],['Carteiras','layers'],['Qualidade','shield']]},
 cliente:{name:'Cliente',person:'Parceiro',initial:'CL',home:'Minha carteira',nav:[['Minha carteira','layout'],['Entregas','check'],['Qualidade','shield']]},
 admin:{name:'Admin',person:'Administrador',initial:'AD',home:'Acessos',nav:[['Acessos','users'],['Carteiras','layers'],['Auditoria','file'],['Integrações','settings']]}
};
const demoTasks=[
 {cnj:'5007488-72.2024.8.21.0048',title:'Validar aptidão para encerramento',kind:'Encerramento',priority:'Alta',due:'Hoje',owner:'Maria',state:'Pendente',uf:'RS'},
 {cnj:'0804365-44.2025.8.10.0031',title:'Confirmar resultado da apelação',kind:'Encerramento',priority:'Alta',due:'Hoje',owner:'Byanca',state:'Em análise',uf:'MA'},
 {cnj:'5009820-43.2026.8.21.0015',title:'Análise de tutela antecipada',kind:'Liminar',priority:'Média',due:'Amanhã',owner:'Ana Lívia',state:'Pendente',uf:'RS'},
 {cnj:'5006309-25.2026.8.21.0019',title:'Conferir comprovante de pagamento',kind:'Pagamento',priority:'Média',due:'13 out',owner:'Maria',state:'Pendente',uf:'RS'},
 {cnj:'5010836-57.2026.8.21.0039',title:'Revisar determinação de defesa',kind:'Defesa',priority:'Baixa',due:'14 out',owner:'Roger',state:'Revisão',uf:'RS'},
 {cnj:'0842536-09.2025.8.12.0001',title:'Confirmar trânsito em julgado',kind:'Encerramento',priority:'Alta',due:'Ontem',owner:'Byanca',state:'Pendente',uf:'MS'}
];
const demoTimeline=[
 ['09 out 2026','Análise operacional','Classificação pendente de validação pelo analista.'],
 ['03 set 2026','Movimento processual','Movimentação de demonstração importada da linha do tempo.'],
 ['23 maio 2026','Trânsito em julgado','Data ilustrativa; confirmar documentação no processo.'],
 ['12 abr 2026','Sentença','Resultado da decisão disponível para conferência.']
];
const demoPortfolios=['Agibank <> MBA','Agibank <> Enter','Nubank <> MBA','Pan <> MBA','Energisa <> Enter'];
const accessRows=[['Visualizar tarefas','✓','✓','—','—','✓'],['Distribuir tarefas','—','✓','—','—','✓'],['Analisar processos','✓','✓','—','—','✓'],['Resultados agregados','Próprio','Equipe','Carteiras','Própria','Todas'],['Ranking e custo','—','Resumo','✓','Restrito','✓'],['Alterar permissões','—','—','—','—','✓'],['Integrações e auditoria','—','—','—','—','✓']];
const commands=['Minha fila','Processos','Resultados','Central operacional','Fila da equipe','Encerramentos','Visão executiva','Ranking','Carteiras','Qualidade','Minha carteira','Entregas','Meu desempenho','Acessos','Auditoria','Integrações'];
const s={role:'supervisor',view:'Central operacional',portfolio:'Agibank <> MBA',theme:(localStorage.getItem('mba-demo-theme')==='lua'?'lua':'sol'),query:'',filter:'Todas',search:false,chosen:demoTasks[0].cnj,step:0,answers:{},completed:[],toast:'',clientTab:'Visão geral',rankTab:'Aging',audit:false};
const iconPaths={
 logo:'<path d="M4 15V5h3l5 7 5-7h3v10"/><path d="M4 19h16"/>',
 inbox:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 13h5l2 3h4l2-3h5"/>',
 folder:'<path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z"/>',
 layout:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
 trend:'<path d="m3 17 6-6 4 3 8-9"/><path d="M15 5h6v6"/>',
 layers:'<path d="m12 2 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5M3 17l9 5 9-5"/>',
 shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-2a6 6 0 0 1 12 0v2"/><path d="M16 5a3 3 0 0 1 0 6m2 5a5 5 0 0 1 3 5"/>',
 file:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h8"/>',
 settings:'<circle cx="12" cy="12" r="3"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M19 5l-2 2M7 17l-2 2"/>',
 search:'<circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/>',
 moon:'<path d="M20 14.5A8 8 0 0 1 9.5 4 8.5 8.5 0 1 0 20 14.5Z"/>',
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M19 5l-2 2M7 17l-2 2"/>',
 arrow:'<path d="M4 12h16m-7-7 7 7-7 7"/>',
 chevron:'<path d="m9 18 6-6-6-6"/>',
 alert:'<path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v5m0 3v.1"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l4 2"/>',
 command:'<path d="M9 7V5a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3v14a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V7"/>',
 download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',
 help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 1c0 2-3 2-3 4m0 3v.1"/>'
};
function ico(n,size=17){return '<svg class="ico" xmlns="http://www.w3.org/2000/svg" width="'+size+'" height="'+size+'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(iconPaths[n]||iconPaths.layout)+'</svg>'}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function button(label,action,kind=''){return '<button class="btn '+kind+'" type="button" data-action="'+action+'">'+label+'</button>'}
function badge(text,kind=''){return '<span class="badge '+kind+'">'+esc(text)+'</span>'}
function txt(n){return new Intl.NumberFormat('pt-BR').format(n)}
function pageHead(tag,title,desc,actions=''){return '<div class="page-head"><div><div class="eyebrow">'+tag+'</div><h1>'+esc(title)+'</h1><p>'+desc+'</p></div><div class="head-actions">'+actions+'</div></div>'}
function stat(label,value,detail='',ic='trend'){return '<div class="stat"><div class="stat-title">'+ico(ic,14)+esc(label)+'</div><div class="stat-value">'+value+'</div><div class="stat-detail">'+detail+'</div></div>'}
function section(label,detail='',action=''){return '<div class="section-head"><div><h2>'+label+'</h2>'+(detail?'<p>'+detail+'</p>':'')+'</div>'+action+'</div>'}
function panel(title,subtitle,content){return '<section class="panel"><div class="panel-head"><div><h3>'+title+'</h3>'+(subtitle?'<p>'+subtitle+'</p>':'')+'</div></div>'+content+'</section>'}
function taskStatus(t){return s.completed.includes(t.cnj)?badge('Concluído','good'):badge(t.state,t.state==='Em análise'?'accent':t.state==='Revisão'?'warn':'')}
function tasksTable({team=false,limit=20}={}){const list=demoTasks.filter(t=>(s.filter==='Todas'||(s.filter==='Alta'&&t.priority==='Alta')||(s.filter==='Vencidas'&&t.due==='Ontem')||(s.filter==='Pendentes'&&!s.completed.includes(t.cnj)))).slice(0,limit);
 const rows=list.map(t=>'<tr><td><button class="row-link" data-action="open-task" data-cnj="'+esc(t.cnj)+'">'+esc(t.cnj)+'</button><div class="muted">'+esc(t.title)+'</div></td><td>'+esc(t.kind)+'</td>'+(team?'<td>'+esc(t.owner)+'</td>':'')+'<td>'+badge(t.priority,t.priority==='Alta'?'bad':t.priority==='Média'?'warn':'')+'</td><td><span class="'+(t.due==='Ontem'?'text-bad':'')+'">'+esc(t.due)+'</span></td><td>'+taskStatus(t)+'</td><td><button class="btn btn-sm" data-action="open-task" data-cnj="'+esc(t.cnj)+'">'+ico('chevron',14)+'</button></td></tr>').join('');
 return '<div class="panel"><div class="table-controls"><label class="muted tiny" for="filter">Filtrar</label><select id="filter" data-filter><option'+(s.filter==='Todas'?' selected':'')+'>Todas</option><option'+(s.filter==='Pendentes'?' selected':'')+'>Pendentes</option><option'+(s.filter==='Alta'?' selected':'')+'>Alta</option><option'+(s.filter==='Vencidas'?' selected':'')+'>Vencidas</option></select><span class="control-spacer"></span><span class="muted tiny">'+list.length+' processos demonstrativos</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Processo / Ação</th><th>Esteira</th>'+(team?'<th>Responsável</th>':'')+'<th>Prioridade</th><th>Prazo</th><th>Situação</th><th></th></tr></thead><tbody>'+rows+'</tbody></table></div></div>'}
function action(title,detail,action,ic='arrow'){return '<button class="action-row" data-action="'+action+'"><span class="action-icon">'+ico(ic,17)+'</span><span class="action-content"><strong>'+title+'</strong><p>'+detail+'</p></span>'+ico('chevron',15)+'</button>'}
function funnel(){const vals=[320,249,141,126,108];const names=['Indícios DataJud','Análises realizadas','Aptos validados','Enviados ao Benner','Encerrados conciliados'];return '<div class="flow-list">'+names.map((n,i)=>'<div class="flow-item"><span class="flow-index">0'+(i+1)+'</span><span class="flow-name">'+n+'</span><span class="flow-track"><span style="width:'+Math.round(vals[i]/vals[0]*100)+'%"></span></span><span class="flow-value">'+vals[i]+'</span></div>').join('')+'</div>'}
function aging(){return '<div class="bars">'+[['0–12 meses',4.2,5],['12–24 meses',3.6,5],['Mais de 24 meses',5.4,5]].map(([n,v,m])=>'<div class="bar-item"><div class="bar-top"><span>'+n+'</span><small>'+String(v).replace('.',',')+'% / '+m+'% da meta</small></div><div class="progress-line"><span style="width:'+Math.min(100,Math.round(v/m*100))+'%"></span></div></div>').join('')+'</div>'}
function analyst(){if(s.view==='Processos')return processes();if(s.view==='Visão do processo')return dossier();if(s.view==='Operação')return operation();if(s.view==='Meu desempenho')return analystResults();if(s.view==='Análise')return analysis();return pageHead('ÁREA DE TRABALHO','Bom trabalho.','As próximas ações estão organizadas por urgência e contexto.',button(ico('arrow',14)+' Iniciar próxima análise','open-next','btn-primary'))+'<div class="kpis">'+stat('Para hoje','12','3 com prioridade alta','clock')+stat('Concluídas hoje','8','<span class="up">+2</span> em relação a ontem','check')+stat('Aguardando revisão','2','Pontos de atenção','alert')+stat('Minha sequência','5 dias','Últimas jornadas de análise','trend')+'</div>'+section('Minha fila','Execute primeiro os casos com prazo mais próximo.')+tasksTable({limit:6})+section('O que precisa da sua atenção')+'<div class="grid-equal">'+panel('Próximo caso','Prazo operacional: hoje','<div class="panel-pad"><div class="eyebrow">ENCERRAMENTO · PRIORIDADE ALTA</div><h2 style="font-size:16px;letter-spacing:-.03em">'+demoTasks[0].cnj+'</h2><p class="muted tiny">Valide a sentença, recurso e trânsito com base nas evidências.</p>'+button('Iniciar análise '+ico('arrow',15),'open-next','btn-primary')+'</div>')+panel('Orientação do dia','Fluxo de análise','<div class="panel-pad"><div class="notice">'+ico('help',18)+'<div><h4>Você responde. O sistema classifica.</h4><p>As decisões são contextualizadas pelas evidências. Não é necessário calcular aging ou interpretar códigos do Benner.</p></div></div></div>')+'</div>'}
function analystResults(){return pageHead('MEUS RESULTADOS','Seu desempenho','Indicadores individuais, sem comparação pública entre colegas.')+'<div class="kpis">'+stat('Analisados hoje','8','Exemplo, não é dado real','check')+stat('Aptos confirmados','4','Após análise humana','shield')+stat('Retornaram para revisão','1','Correção demonstrativa','alert')+stat('Pendentes','12','Minha fila atual','clock')+'</div>'+section('Sua evolução')+panel('Produção por dia','Evolução demonstrativa de análises concluídas','<div class="bars">'+[['Segunda-feira',5,10],['Terça-feira',7,10],['Quarta-feira',8,10],['Quinta-feira',6,10],['Sexta-feira',8,10]].map(([n,v,m])=>'<div class="bar-item"><div class="bar-top">'+n+'<b>'+v+' análises</b></div><div class="progress-line"><span style="width:'+(v/m*100)+'%"></span></div></div>').join('')+'</div>') }

function processes(){return pageHead('PROCESSOS','Cada processo, uma história.','Evidências, tarefas relacionadas, classificações e histórico em uma única página.',button(ico('search',14)+' Buscar CNJ','search-open'))+'<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Número do processo</th><th>Carteira</th><th>UF</th><th>Próxima ação</th><th></th></tr></thead><tbody>'+demoTasks.map(t=>'<tr><td><button class="row-link" data-action="open-process" data-cnj="'+esc(t.cnj)+'">'+esc(t.cnj)+'</button><div class="muted">Movimentações e tarefas vinculadas</div></td><td>'+esc(s.portfolio)+'</td><td>'+t.uf+'</td><td>'+badge(t.kind,t.priority==='Alta'?'accent':'')+'</td><td><button class="btn btn-sm" data-action="open-process" data-cnj="'+esc(t.cnj)+'">Abrir '+ico('chevron',13)+'</button></td></tr>').join('')+'</tbody></table></div></section>'+section('Modelo de dossiê')+'<div class="notice">'+ico('folder',19)+'<div><h4>Entidade canônica, não cópia da Enter</h4><p>O CNJ reúne andamentos do DataJud, contexto jurídico, tarefas internas, análise e confirmação. Esta demonstração não consulta dados reais.</p></div></div>'}
function dossier(){const t=demoTasks.find(x=>x.cnj===s.chosen)||demoTasks[0];return pageHead('DOSSÍÊ PROCESSUAL',s.chosen,'Uma visão única de andamento, execução e histórico.',button('Criar tarefa '+ico('arrow',14),'create-process-task','btn-primary'))+'<div class="process-details"><span>Carteira: '+esc(s.portfolio)+'</span><span>UF: '+t.uf+'</span><span>Tipo: '+esc(t.kind)+'</span>'+badge('Demonstração','accent')+'</div><div class="kpis">'+stat('Tarefas vinculadas',String(demoTasks.filter(x=>x.cnj===s.chosen).length),'Inclui tarefas criadas nesta sessão','inbox')+stat('Prioridade',t.priority,'Operacional','clock')+stat('Último andamento','03 set','Data ilustrativa','file')+stat('Conciliação','Pendente','Verificar origem e dados','shield')+'</div>'+section('Painel processual')+'<div class="grid-two">'+panel('Tarefas do processo','Criar tarefas sem perder o histórico do CNJ','<div class="action-list">'+demoTasks.filter(x=>x.cnj===s.chosen).map(x=>action(esc(x.title),x.kind+' · '+x.priority+' · '+x.due,'start-process-analysis','check')).join('')+'</div><div class="panel-pad">'+button(ico('check',15)+' Iniciar análise de encerramento','start-process-analysis','btn-primary')+'</div>')+panel('Timeline · DataJud','Movimentações de exemplo, sem consulta à API','<div class="timeline">'+demoTimeline.map(([date,title,desc])=>'<div class="timeline-item"><time>'+date+'</time><h4>'+title+'</h4><p>'+desc+'</p></div>').join('')+'</div>')+'</div>'+section('Registro da decisão')+'<div class="notice">'+ico('shield',18)+'<div><h4>Histórico rastreável</h4><p>Em produção, cada tarefa, resposta e lançamento deve conter fonte, responsável, timestamp, versão de regra e idempotência. Não sobrescrever movimentações.</p></div></div>'}
function operation(){const modules=[['Encerramentos','Classificação, validação e envio conciliado','layers'],['Pagamentos','Conferência de comprovantes e situações','check'],['Liminar','Indícios de tutela e resultado de decisão','shield'],['Defesas','Prazo e determinação de contestação','file'],['Protocolos','Correspondência e documentação','folder'],['Acordos','Conferência e saneamento de registros','users']];return pageHead('OPERAÇÃO','Uma operação. Várias esteiras.','Todos os fluxos seguem as mesmas regras de navegação, prioridade e confirmação.')+'<div class="grid-equal">'+modules.map(([name,desc,ic])=>'<section class="panel panel-pad"><div style="display:flex;gap:13px;align-items:flex-start"><div class="action-icon">'+ico(ic,18)+'</div><div style="flex:1"><h3 class="panel-title">'+name+'</h3><p class="muted tiny" style="line-height:1.6">'+desc+'</p>'+button('Abrir esteira '+ico('arrow',13),'module-'+name,'btn-sm')+'</div></div></section>').join('')+'</div>'+section('Como funcionam as esteiras')+'<div class="notice">'+ico('check',18)+'<div><h4>Um padrão de execução para todas as carteiras</h4><p>Importar ou localizar → validar evidências → responder Q&A → registrar decisão → conciliar resultado. A disponibilidade das automações depende de cada cliente, não do layout.</p></div></div>'}
const questions=[
 {question:'Qual foi o resultado da sentença?',description:'Confira o dispositivo da sentença nos autos.',opts:['Procedente','Parcialmente procedente','Improcedente','Extinção']},
 {question:'Houve interposição de apelação?',description:'Considere apenas recurso pertinente ao desfecho da sentença.',opts:['Sim','Não']},
 {question:'Qual foi o resultado da apelação?',description:'Registre a decisão de 2ª instância, quando houver.',opts:['Provido','Improvido','Sem acórdão']},
 {question:'Houve trânsito em julgado?',description:'A data será registrada a partir de documento ou movimento confiável.',opts:['Sim','Não','Não identificado']},
 {question:'Há execução ou cumprimento em andamento?',description:'Verifique o histórico mais recente antes de confirmar.',opts:['Sim','Não','Não foi possível determinar']},
 {question:'Você concorda com a classificação?',description:'Confirme a proposta do classificador ou sinalize divergência para revisão.',opts:['Sim','Não — classificação errada']}
];
function analysis(){const t=demoTasks.find(x=>x.cnj===s.chosen)||demoTasks[0],q=questions[Math.min(s.step,questions.length-1)],ans=s.answers[s.step];return pageHead('ANÁLISE DE ENCERRAMENTO','Decida com evidências.','Perguntas em sequência · validação humana obrigatória',button(ico('help',15)+' Preciso de ajuda','help'))+'<div class="process-details"><b>'+esc(t.cnj)+'</b><span>Carteira: '+esc(s.portfolio)+'</span><span>Tipo: '+t.kind+'</span>'+badge('Dados de demonstração','accent')+'</div><div class="two-columns"><section class="panel"><div class="question-box"><div style="display:flex;align-items:center;justify-content:space-between"><span class="eyebrow">ETAPA '+(s.step+1)+' DE '+questions.length+'</span><span class="muted tiny">Rascunho local</span></div><div class="step-bar">'+questions.map((_,i)=>'<span class="'+(i<=s.step?'current':'')+'"></span>').join('')+'</div><h2>'+q.question+'</h2><p>'+q.description+'</p>'+q.opts.map((opt,i)=>'<button class="choice '+(ans===opt?'selected':'')+'" data-action="answer" data-choice="'+i+'"><span>'+opt+'</span>'+(ans===opt?ico('check',16):'<span style="width:15px;height:15px;border:1px solid var(--line);border-radius:50%"></span>')+'</button>').join('')+'<div class="question-footer">'+button('Voltar','step-back','btn-quiet')+button(s.step===questions.length-1?'Concluir simulação':'Próxima pergunta '+ico('arrow',15),'step-next','btn-primary')+'</div></div></section><div><section class="panel">'+panelInnerTitle('Linha do tempo · DataJud','EVENTOS ILUSTRATIVOS')+'<div class="timeline">'+demoTimeline.map(([date,title,desc])=>'<div class="timeline-item"><time>'+date+'</time><h4>'+title+'</h4><p>'+desc+'</p></div>').join('')+'</div></section><div style="height:13px"></div><div class="notice">'+ico('shield',18)+'<div><h4>Classificação não confirmada</h4><p>Somente uma validação efetiva deve gerar o status de aptidão. Esta prévia não envia dados à API ou ao Benner.</p></div></div></div></div>'}
function panelInnerTitle(a,b){return '<div class="panel-head"><h3>'+a+'</h3><span class="muted tiny">'+b+'</span></div>'}
function supervisor(){if(s.view==='Fila da equipe')return pageHead('GESTÃO DE PESSOAS','Fila da equipe','Visão operacional por responsável, prioridade e prazo.',button(ico('download',14)+' Exportar amostra','export'))+tasksTable({team:true})+section('Capacidade','Sinais para redistribuição, sem pontuação de vigilância.')+panel('Alocação atual','Quantidade de tarefas fictícias por responsável','<div class="bars">'+[['Maria',2,4],['Byanca',2,4],['Ana Lívia',1,4],['Roger',1,4]].map(([n,v,m])=>'<div class="bar-item"><div class="bar-top">'+n+'<b>'+v+' processos</b></div><div class="progress-line"><span style="width:'+(v/m*100)+'%"></span></div></div>').join('')+'</div>');if(s.view==='Encerramentos')return closing();if(s.view==='Operação')return operation();if(s.view==='Visão do processo')return dossier();if(s.view==='Resultados')return manager(true);if(s.view==='Processos'||s.view==='Análise')return s.view==='Análise'?analysis():processes();
 return pageHead('GESTÃO OPERACIONAL','O que precisa acontecer hoje?','A supervisão deve enxergar o gargalo antes que ele vire atraso.',button(ico('arrow',14)+' Abrir fila da equipe','team','btn-primary'))+'<div class="kpis">'+stat('Análises pendentes','128','<span class="down">18</span> com prazo crítico','inbox')+stat('Aptos sem envio','15','Prioridade de efetivação','check')+stat('Em revisão','9','Possível retrabalho','alert')+stat('Efetivados no mês','108','Conciliação demonstrativa','trend')+'</div>'+section('Decisões recomendadas','O sistema sugere próximas ações, não altera decisões jurídicas.')+'<div class="grid-two">'+panel('Oportunidades de execução','Ordenadas por impacto, prazo e prontidão','<div class="action-list">'+action('Concluir envios já validados','15 casos aptos ainda não avançaram à etapa de confirmação.','closing','arrow')+action('Redistribuir tarefas vencidas','6 processos da fila demonstrativa exigem triagem de prazo.','team','clock')+action('Revisar divergências do classificador','Conferir evidências e justificativas registradas pelo analista.','closing','shield')+'</div>')+panel('Conversão do encerramento','Base de demonstração, não é dado de produção',funnel())+'</div>'+section('Acompanhar a equipe','Os processos são o objeto principal de trabalho.',button('Ver todas','team','btn-quiet'))+tasksTable({team:true,limit:5})}
function closing(){return pageHead('OPERAÇÃO','Encerramentos','Do indício DataJud ao encerramento reconhecido.',button(ico('download',14)+' Exportar amostra','export'))+'<div class="kpis">'+stat('Indícios','320','Coleta demonstrativa','search')+stat('Aptos validados','141','Confirmação humana','check')+stat('Enviados ao Benner','126','Status de integração','arrow')+stat('Conciliados','108','Reconciliação de demonstração','shield')+'</div>'+section('Funil completo')+'<div class="grid-two">'+panel('Conversão operacional','Cada transição exige origem, responsável e registro temporal',funnel())+panel('Pontos de retenção','Sugestões de ação para o supervisor','<div class="action-list">'+action('15 aptos sem envio','Conferir fila e pré-requisitos de integração.','show-toast','alert')+action('18 envios sem conciliação','Revisar retornos antes de contabilizar resultado oficial.','show-toast','clock')+'</div>')+'</div>'+section('Casos em andamento')+tasksTable({team:true})}
function manager(fromSupervisor=false){if(!fromSupervisor&&s.view==='Ranking')return ranking();if(!fromSupervisor&&s.view==='Carteiras')return portfolioView(false);if(!fromSupervisor&&s.view==='Qualidade')return quality(false);return pageHead('GESTÃO ESTRATÉGICA',fromSupervisor?'Resultados da operação':'Visão executiva','Resultados, riscos e distância até a meta — sem ruído da execução individual.',button(ico('download',14)+' Exportar resumo','export'))+'<div class="kpis">'+stat('Encerrados','108','Conciliação demonstrativa','check')+stat('Aptos em trânsito','33','Validados, ainda não conciliados','clock')+stat('Metas de aging','1 / 3','Faixas com meta atingida','trend')+stat('Pontos sob risco','—','Exigem base oficial para cálculo','shield')+'</div>'+section('Leitura executiva')+'<div class="grid-two">'+panel('Atingimento por aging','Metas de demonstração; não usar como nota oficial',aging())+panel('Decisões da semana','Prioridades para o fechamento','<div class="action-list">'+action('Concentrar execução no aging de 12–24 meses','Faixa está mais distante de 5% na simulação.','ranking','trend')+action('Confirmar custo e denominadores do edital','Sem conciliação não existe nota fechada.','ranking','shield')+action('Conciliar 18 envios pendentes','Evitar contar tentativa de envio como encerramento realizado.','closing','check')+'</div>')+'</div>'+section('Leitura do ranking')+panel('Componentes de pontuação','Pesos de referência; verificação do edital e competência obrigatória','<div class="split-card">'+[['Custo médio','3,2 pts'],['Aging','2,4 pts'],['Vitórias','2,0 pts'],['Acordos','1,4 pts'],['Qualitativo','1,0 pt']].map(([a,b])=>'<div class="split-metric"><span>'+a+'</span><strong>'+b+'</strong><span>Indicador a conciliar</span></div>').join('')+'</div>') }
function ranking(){return pageHead('PERFORMANCE','Ranking Agibank','Separação explícita entre simulação, previsão e resultados oficiais.',button(ico('download',14)+' Exportar referência','export'))+'<div class="notice">'+ico('alert',18)+'<div><h4>Nota não calculada</h4><p>O resultado oficial depende dos denominadores do edital, custo apurado, dados de vitória/acordo e critérios qualitativos. Os números ilustrativos abaixo não compõem uma nota real.</p></div></div>'+section('Metas e componentes')+'<div class="grid-two">'+panel('Encerramentos por aging','Metas por faixa, exemplo Agibank MBA',aging())+panel('Composição dos 10 pontos','Estrutura de referência para validação','<div class="panel-pad">'+[['Custo médio','3,2'],['Encerramentos por aging','2,4'],['Vitórias','2,0'],['Acordos','1,4'],['Qualitativo','1,0']].map(([n,v])=>'<div class="ranking-row"><span>'+n+'</span><div class="progress-line"><span style="width:'+(Number(v.replace(',','.'))/3.2*100)+'%"></span></div><b>'+v+'</b></div>').join('')+'<p class="muted tiny">Bônus e detratores devem ser conciliados separadamente.</p></div>')+'</div>'+section('Metas de desfecho')+'<div class="kpis">'+stat('Taxa-meta de vitória','76%','Régua de referência','check')+stat('Taxa-meta de acordo','14%','Régua de referência','trend')+stat('Limite de custo MBA','R$ 1.000','Conferir critérios de apuração','shield')+stat('Bônus / detratores','± 3','Sujeitos às regras oficiais','alert')+'</div>'}
function portfolioView(client){return pageHead(client?'PORTAL DO CLIENTE':'PORTFÓLIO',client?'Minha carteira':'Carteiras sob gestão',client?'Transparência sobre entregas e qualidade da carteira contratada.':'Comparações por carteira sem misturar regras e métricas.')+'<div class="kpis">'+stat('Processos acompanhados','2.480','Amostra demonstrativa','folder')+stat('Entregas no período','108','Confirmadas na simulação','check')+stat('Em processamento','18','Ainda não concluídos','clock')+stat('Atualização','09 out','Referência ilustrativa','shield')+'</div>'+section('Acompanhamento')+'<div class="grid-two">'+panel('Entregas por etapa','Contagem agregada, sem informações internas da equipe',funnel())+panel('Evolução do mês','Simulação por semana','<div class="bars">'+[['Semana 01',38,50],['Semana 02',49,50],['Semana 03',42,50],['Semana 04',27,50]].map(([n,v,m])=>'<div class="bar-item"><div class="bar-top">'+n+'<b>'+v+'</b></div><div class="progress-line"><span style="width:'+(v/m*100)+'%"></span></div></div>').join('')+'</div>')+'</div>'}
function quality(client){return pageHead('QUALIDADE',client?'Qualidade das entregas':'Riscos e qualidade','Indicadores interpretáveis com fonte e data de atualização.')+'<div class="kpis">'+stat('Revisões','9','Amostra ilustrativa','alert')+stat('Divergências','3','Necessitam validação','shield')+stat('Reativações','2','Verificar causa e competência','clock')+stat('Envios conciliados','108','Amostra ilustrativa','check')+'</div>'+section('Sinais relevantes')+'<div class="grid-two">'+panel('Qualidade do ciclo','Ocorrências agregadas e motivos','<div class="action-list">'+(client?action('Entregas confirmadas','Resumo sem acesso aos registros internos de auditoria.','show-toast','check')+action('Correções acompanhadas','Correções são demonstradas em agregados por competência.','show-toast','shield'):action('Divergências no classificador','Auditar fonte, tipo e intervenção humana.','show-toast','shield')+action('Retrabalho e reativações','Identificar causas e corrigir processos recorrentes.','show-toast','alert'))+'</div>')+panel('Origem dos números','Leitura responsável','<div class="panel-pad"><div class="notice">'+ico('shield',18)+'<div><h4>Transparência sem suposições</h4><p>Somente a base oficial conciliada gera indicador definitivo. Dados internos ou individuais não ficam disponíveis no portal do cliente.</p></div></div></div>')+'</div>'}
function client(){if(s.view==='Qualidade')return quality(true);if(s.view==='Entregas')return portfolioView(true);return pageHead('PORTAL DO CLIENTE','Sua carteira, com clareza.','Status de entregas, evolução e qualidade, sem a complexidade dos nossos fluxos internos.',button(ico('download',14)+' Exportar resumo','export'))+'<div class="kpis">'+stat('Processos monitorados','2.480','Demonstração','folder')+stat('Entregas confirmadas','108','No período ilustrativo','check')+stat('Em processamento','18','Ainda não efetivados','clock')+stat('Última atualização','09 out','Dados de demonstração','shield')+'</div>'+section('Acompanhamento da carteira')+'<div class="grid-two">'+panel('Evolução das entregas','Etapas agregadas da operação',funnel())+panel('Resumo transparente','O que a base contabiliza','<div class="panel-pad"><div class="notice">'+ico('shield',18)+'<div><h4>Dados limitados à sua carteira</h4><p>O portal não mostra usuários internos, filas de equipe, configurações, custos de outras carteiras nem decisões automatizadas ainda não validadas.</p></div></div></div>')+'</div>'}
function matrix(){return '<div class="table-wrap"><table class="matrix"><thead><tr><th>Capacidade</th><th>Analista</th><th>Supervisor</th><th>Gerente</th><th>Cliente</th><th>Admin</th></tr></thead><tbody>'+accessRows.map(([action,...flags])=>'<tr><td>'+action+'</td>'+flags.map(x=>'<td>'+(x==='✓'?'<span class="text-good">✓</span>':x==='—'?'<span class="muted">—</span>':badge(x))+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
function admin(){if(s.view==='Carteiras')return adminPortfolio();if(s.view==='Auditoria')return audit();if(s.view==='Integrações')return integrations();return pageHead('ADMINISTRAÇÃO','Acessos e governança','Papéis globais + permissões específicas por módulo, carteira e operação.',button(ico('help',14)+' Guia de segurança','admin-help'))+'<div class="kpis">'+stat('Papéis definidos','5','RBAC de referência','users')+stat('Carteiras disponíveis','5','Acesso por vínculo','layers')+stat('Permissões críticas','4','Edição restrita ao Admin','shield')+stat('Mudanças auditáveis','100%','Requisito de implementação','file')+'</div>'+section('Matriz de capacidades','Planejamento conceitual, não substitui políticas de backend.')+panel('Permissões por perfil','Gerente inclui sócio, coordenação, diretoria e CEO; suas carteiras continuam delimitadas.',matrix())+section('Atribuição de usuário')+panel('Permissões detalhadas','Fluxo proposto para o Admin','<div class="panel-pad"><div class="grid-equal"><div><label class="sb-label" style="padding:0;display:block;margin-bottom:9px">Usuário (demonstração)</label><select class="form-select" aria-label="Usuário demonstrativo"><option>Usuário de demonstração</option></select></div><div><label class="sb-label" style="padding:0;display:block;margin-bottom:9px">Perfil de acesso</label><select class="form-select" aria-label="Perfil a atribuir" id="assign-role"><option>Analista</option><option>Supervisor</option><option>Gerente</option><option>Cliente</option><option>Admin</option></select></div></div><p class="muted tiny">Em produção, esta ação exigirá checagem de privilégio, confirmação e trilha imutável de auditoria.</p>'+button('Simular atribuição','admin-assign','btn-primary')+'</div>')}
function adminPortfolio(){return pageHead('ADMINISTRAÇÃO','Isolamento das carteiras','Escopo por carteira, organização e permissão, aplicado também no servidor.')+panel('Política por carteira','Exemplo de módulos previstos para cada operação','<div class="table-wrap"><table class="data-table"><thead><tr><th>Carteira</th><th>Operação</th><th>Processos</th><th>Automações</th><th>Dados do cliente</th></tr></thead><tbody>'+demoPortfolios.map((p,i)=>'<tr><td><strong>'+p+'</strong></td><td>'+badge('Ativa','good')+'</td><td>✓</td><td>'+(i===0||i===1?'Escopo habilitado':'Sob autorização')+'</td><td>Isolados</td></tr>').join('')+'</tbody></table></div>')+'<div class="footer-note">A seleção de carteira nunca deve ser usada como segurança. A API deve restringir consultas, exportações e ações pelo vínculo autenticado.</div>'}
function audit(){return pageHead('ADMINISTRAÇÃO','Auditoria','Rastreabilidade das ações, classificações e privilégios.')+panel('Eventos que precisam de rastreio','Modelo sugerido, não são logs reais','<div class="action-list">'+action('Mudança de perfil e acesso','Quem aprovou, antes/depois, hora e carteira autorizada.','show-toast','users')+action('Validação do classificador','Respostas, evidências, versão das regras e correções.','show-toast','shield')+action('Envio e conciliação no Benner','Job, idempotência, retorno, responsável e hash de evento.','show-toast','arrow')+action('Exportações e consulta a dados','Ator, finalidade, carteira, volume e momento.','show-toast','file')+'</div>')}
function integrations(){return pageHead('ADMINISTRAÇÃO','Integrações','Confiabilidade e integridade dos fluxos operacionais.')+'<div class="kpis">'+stat('DataJud','A validar','Situação real não consultada','layers')+stat('Benner','A validar','Situação real não consultada','shield')+stat('Supabase','A validar','Situação real não consultada','folder')+stat('Workers','A validar','Situação real não consultada','settings')+'</div>'+section('Princípios de operação')+'<div class="grid-equal">'+panel('Nenhuma métrica sem origem','Requisito para produção','<div class="panel-pad"><p class="muted tiny">Cada número deve guardar fonte, competência, última atualização, status e versão da regra. Dado ausente deve ser “Indisponível”, nunca zero inventado.</p></div>')+panel('Políticas no servidor','Requisito para produção','<div class="panel-pad"><p class="muted tiny">Papéis, vínculos por carteira, RLS e autorização de rotas/API devem ser aplicados antes de ativar qualquer login Cliente ou Gerente.</p></div>')+'</div>'}
function roleBody(){if(s.role==='analista')return analyst();if(s.role==='supervisor')return supervisor();if(s.role==='gerente')return manager();if(s.role==='cliente')return client();return admin()}
function sidebar(){const r=roles[s.role];return '<aside class="sidebar"><div class="brand"><div class="brand-mark">M.</div><div><div class="brand-name">MBA Backoffice</div><div class="brand-description">A operação, com clareza.</div></div></div><div class="sb-label">Espaço de trabalho</div><nav class="side-links" aria-label="Navegação principal">'+r.nav.map(([name,ic])=>'<button type="button" class="side-link '+(s.view===name?'active':'')+'" data-view="'+esc(name)+'">'+ico(ic,17)+'<span>'+name+'</span>'+(name==='Minha fila'?'<span class="counter">12</span>':'')+'</button>').join('')+'</nav><div class="side-bottom"><div class="portfolio-block"><label for="portfolio">Carteira</label><select id="portfolio" class="port-select" data-portfolio>'+ (s.role==='cliente'?['Agibank <> MBA']:demoPortfolios).map(p=>'<option '+(s.portfolio===p?'selected':'')+'>'+p+'</option>').join('')+'</select></div><div class="side-profile"><div class="avatar">'+r.initial+'</div><div class="identity"><div class="profile-name">'+r.person+'</div><div class="profile-role">'+r.name+' · Prévia</div></div></div></div></aside>'}
function searchOverlay(){if(!s.search)return '';const q=s.query.toLowerCase().trim(),options=[...roles[s.role].nav.map(([name])=>({label:name,kind:'Navegação',name:name}))].concat(s.role==='analista'||s.role==='supervisor'?demoTasks.map(t=>({label:t.cnj,kind:t.title,name:'process:'+t.cnj})):[]).filter(t=>!q||t.label.toLowerCase().includes(q)||t.kind.toLowerCase().includes(q)).slice(0,9);return '<div class="modal-backdrop" data-action="search-close"><div class="command" role="dialog" aria-modal="true" aria-label="Buscar"><input id="cmd-input" autofocus autocomplete="off" placeholder="Buscar página ou processo..." value="'+esc(s.query)+'" aria-label="Busca rápida"><div class="command-results">'+(options.length?options.map(t=>'<button data-action="command-pick" data-target="'+esc(t.name)+'">'+ico(t.name.startsWith('process:')?'folder':'search',16)+'<span style="flex:1">'+esc(t.label)+'</span><span class="muted tiny">'+esc(t.kind)+'</span></button>').join(''):'<div class="empty">Nenhum resultado encontrado.</div>')+'</div><div class="command-foot">Esc para fechar · Esta busca consulta somente os exemplos locais.</div></div></div>'}
function toast(message){s.toast=message;render();setTimeout(()=>{if(s.toast===message){s.toast='';document.querySelector('.toast')?.remove()}},3400)}
function render(){document.documentElement.setAttribute('data-theme',s.theme);const r=roles[s.role];document.getElementById('app').innerHTML='<div class="app-shell">'+sidebar()+'<main class="workspace"><header class="topbar"><div class="breadcrumbs">'+ico('layers',14)+' MBA <span style="color:var(--soft)">/</span> <b>'+esc(s.view)+'</b></div><div class="top-spacer"></div><button class="search-trigger" data-action="search-open">'+ico('search',15)+'<span>Buscar processo ou módulo</span><kbd class="key">⌘ K</kbd></button><div class="switcher"><label for="role-select">Visualizar como</label><select id="role-select" data-role>'+Object.entries(roles).map(([k,v])=>'<option value="'+k+'" '+(s.role===k?'selected':'')+'>'+v.name+'</option>').join('')+'</select></div><button class="icon-button" data-action="theme" aria-label="Alternar tema">'+ico(s.theme==='sol'?'moon':'sun',18)+'</button></header><div class="prototype-strip"><span><strong>PROTÓTIPO INTERATIVO</strong> · Cinco experiências por perfil · Dados 100% fictícios</span><small>O seletor de papéis existe apenas nesta demonstração. Não concede permissões reais.</small></div><div class="main-scroll"><div class="main-inner">'+roleBody()+'<div class="footer-note">MBA Backoffice Reimagined · Sol / Lua · Protótipo sem API, autenticação ou dados de produção</div></div></div></main></div>'+searchOverlay()+(s.toast?'<div role="status" class="toast">'+ico('check',15)+' '+esc(s.toast)+'</div>':'');if(s.search){const field=document.getElementById('cmd-input');if(field){field.focus();field.setSelectionRange(field.value.length,field.value.length)}}}
function csvEscape(str){return '"'+String(str).replace(/"/g,'""')+'"'}
function exportDemo(){const rows=s.role==='cliente'||s.role==='gerente'?[['Indicador','Valor','Status'],['Entregas confirmadas',108,'Demonstração'],['Em processamento',18,'Demonstração']]:[['CNJ','Esteira','Prioridade','Responsável','Situação'],...demoTasks.map(t=>[t.cnj,t.kind,t.priority,t.owner,s.completed.includes(t.cnj)?'Concluído':t.state])];const csv='\ufeff'+rows.map(row=>row.map(csvEscape).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='mba-backoffice-prototipo-'+s.role+'.csv';document.body.append(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);toast('Arquivo demonstrativo exportado.')}
document.addEventListener('click',e=>{const target=e.target.closest('[data-action],[data-view]');if(!target)return;if(target.hasAttribute('data-view')){s.view=target.dataset.view;s.filter='Todas';render();return}const a=target.dataset.action;if(a==='search-close'){if(e.target.closest('.command'))return;s.search=false;s.query='';render();return}
if(a==='search-open'){s.search=true;render();return}
if(a==='command-pick'){const name=target.dataset.target;s.search=false;s.query='';if(name.startsWith('process:')){s.chosen=name.slice(8);s.view='Análise';s.step=0;s.answers={}}else{s.view=name}render();return}
if(a==='theme'){s.theme=s.theme==='sol'?'lua':'sol';localStorage.setItem('mba-demo-theme',s.theme);render();return}
if(a==='open-process'){s.chosen=target.dataset.cnj;s.view='Visão do processo';render();return}
if(a==='create-process-task'){demoTasks.push({cnj:s.chosen,title:'Nova tarefa de acompanhamento',kind:'Acompanhamento',priority:'Média',due:'Amanhã',owner:'Equipe',state:'Pendente',uf:'RS'});toast('Tarefa criada apenas nesta simulação.');return}
if(a==='start-process-analysis'){s.view='Análise';s.step=0;s.answers={};render();return}
if(a&&a.startsWith('module-')){const module=a.slice(7);if(module==='Encerramentos'&&s.role==='supervisor'){s.view='Encerramentos';render()}else if(module==='Encerramentos'){s.view='Minha fila';render()}else{toast(module+': fluxo demonstrativo; a implementação real preservará a lógica atual.')}return}
if(a==='open-next'||a==='open-task'){s.chosen=a==='open-task'?target.dataset.cnj:demoTasks[0].cnj;s.step=0;s.answers={};s.view='Análise';render();return}
if(a==='answer'){s.answers[s.step]=questions[s.step].opts[Number(target.dataset.choice)];render();return}
if(a==='step-back'){if(s.step===0){s.view=roles[s.role].home}else{s.step--}render();return}
if(a==='step-next'){if(!s.answers[s.step]){toast('Selecione uma resposta antes de prosseguir.');return}if(s.step<questions.length-1){if(s.step===1&&s.answers[1]==='Não'){s.answers[2]='Não se aplica';s.step=3}else{s.step++}render();return}if(s.answers[questions.length-1].startsWith('Não')){toast('Divergência registrada apenas nesta simulação.');s.view=roles[s.role].home;render();return}s.completed.push(s.chosen);s.view=roles[s.role].home;toast('Análise de demonstração concluída. Nenhum dado real foi alterado.');return}
if(a==='team'){s.view='Fila da equipe';render();return}if(a==='closing'){if(s.role==='supervisor'){s.view='Encerramentos';render()}else toast('Ação disponível para supervisão.');return}
if(a==='ranking'){if(s.role==='gerente'){s.view='Ranking';render()}else toast('Ranking executivo: visão autorizada por perfil.');return}
if(a==='export'){exportDemo();return}
if(a==='help'){toast('Solicitação demonstrativa: em produção abre o suporte e registra o CNJ.');return}
if(a==='admin-help'){toast('Em produção, a permissão deve ser verificada pelo backend e pelo banco.');return}
if(a==='admin-assign'){toast('Simulação concluída. Nenhuma credencial foi criada ou alterada.');return}
if(a==='show-toast'){toast('Exemplo de ação gerencial. Nenhum registro real foi alterado.');return}
});
document.addEventListener('change',e=>{const t=e.target;if(t.matches('[data-role]')){s.role=t.value;s.view=roles[s.role].home;s.portfolio=s.role==='cliente'?'Agibank <> MBA':s.portfolio;s.filter='Todas';s.search=false;s.answers={};render()}if(t.matches('[data-portfolio]')){s.portfolio=t.value;render()}if(t.matches('[data-filter]')){s.filter=t.value;render()}});
document.addEventListener('input',e=>{if(e.target.id==='cmd-input'){s.query=e.target.value;const pos=e.target.selectionStart;render();const f=document.getElementById('cmd-input');f?.setSelectionRange(pos,pos)}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();s.search=!s.search;render()}if(e.key==='Escape'&&s.search){s.search=false;s.query='';render()}});
render();
